sonar.projectKey=a01722831_Sem6EspinaBifida
sonar.organization=a01722831

sonar.exclusions=appespinabifida/Base de Datos Oracle


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=Sem6EspinaBifida
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8