import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://sem6-espina-bifida.vercel.app/');
  await page.getByRole('textbox', { name: 'Usuario' }).click();
  await page.getByRole('textbox', { name: 'Usuario' }).fill('test@test.com');
  await page.getByRole('textbox', { name: 'Contraseña' }).click();
  await page.getByRole('textbox', { name: 'Contraseña' }).fill('testpassword');
  await page.getByRole('button', { name: 'Iniciar Sesión' }).click();
  await page.getByLabel('Filtrar por estatus').selectOption('Inactivo');
  await page.locator('div').filter({ hasText: /^Cargar más datos$/ }).click();
  await page.getByLabel('Filtrar por estatus').selectOption('Activo');
  await page.getByRole('cell', { name: 'Bruno Diaz Morales' }).click();
  await page.getByRole('button', { name: 'Editar' }).click();
  await page.getByRole('combobox').nth(2).selectOption('Inactivo');
  await page.getByText('Modo edición activadoCancelarGuardar cambios').click();
  await page.getByRole('button', { name: 'Guardar cambios' }).click();
  await page.getByLabel('Filtrar por estatus').selectOption('Inactivo');
  await page.getByRole('cell', { name: 'Inactivo' }).click();
  await page.getByText('EstatusInactivo').click();
  await page.getByRole('button', { name: 'Editar' }).click();
  await page.getByRole('combobox').nth(2).selectOption('Activo');
  await page.getByRole('button', { name: 'Guardar cambios' }).click();
  await page.getByRole('link', { name: 'Servicios' }).click();
  await page.getByRole('button', { name: 'Nuevo servicio' }).click();
  await page.getByRole('button', { name: 'Consulta' }).click();
  await page.getByRole('textbox', { name: 'Nombre o número de asociado...' }).click();
  await page.getByRole('textbox', { name: 'Nombre o número de asociado...' }).fill('j');
  await page.getByRole('button', { name: 'Jose Carlos Pendulos Perez Asociado #93' }).click();
  await page.getByRole('combobox').nth(4).selectOption('seguimiento');
  await page.getByRole('combobox').nth(5).selectOption('54');
  await page.getByRole('dialog', { name: 'Nueva consulta' }).locator('input[type="date"]').fill('2026-05-23');
  await page.getByRole('textbox', { name: ':00' }).click();
  await page.getByRole('textbox', { name: ':00' }).fill('12:30');
  await page.locator('.rounded-lg.border.border-slate-200.bg-slate-50.px-2').selectOption('PM');
  await page.getByRole('textbox', { name: '0.00' }).click();
  await page.getByRole('textbox', { name: '0.00' }).fill('30.000');
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'Guardar consulta' }).click();
  await page.getByText('ServiciosNuevo servicio').click();
  await page.getByLabel('Filtrar por estatus').selectOption('Pendiente');
  await page.getByRole('cell', { name: 'Pendiente' }).first().click();
  await page.getByText('Pendiente').nth(1).click();
  await page.getByRole('link', { name: 'Editar consulta' }).click();
  await page.getByRole('combobox').nth(1).selectOption('Completado');
  await page.getByRole('button', { name: 'Guardar cambios' }).click();
  await page.getByRole('main').getByRole('link', { name: 'Servicios' }).click();
});