-- =============================================
-- Espina Bífida de Nuevo León - Caballos del Castillo
-- Oracle SQL Compatible
-- =============================================

-- Articulo

CREATE TABLE "ADMIN"."ARTICULO" 
   (	"ID_ARTICULO" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"CLAVE" VARCHAR2(50 BYTE), 
	"DESCRIPCION" VARCHAR2(200 BYTE), 
	"UNIDAD" VARCHAR2(50 BYTE), 
	"CUOTA_RECUPERACION" NUMBER(10,2), 
	"INVENTARIO_ACTUAL" NUMBER, 
	"STOCK_MINIMO" NUMBER, 
	"CATEGORIA" VARCHAR2(100 BYTE), 
	"PROVEEDOR" VARCHAR2(150 BYTE), 
	"NOMBRE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
ALTER TABLE "ADMIN"."ARTICULO" ADD PRIMARY KEY ("ID_ARTICULO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
ALTER TABLE "ADMIN"."ARTICULO" ADD UNIQUE ("CLAVE")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
ALTER TABLE "ADMIN"."ARTICULO" ADD CONSTRAINT "CHK_MEDICAMENTO_TIPO" CHECK (categoria in ('medicamento', 'equipo medico', 'material medico', 'consumible')) ENABLE;

-- Asociados

CREATE TABLE "ADMIN"."ASOCIADO" 
   (	"ID_ASOCIADO" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"CURP" VARCHAR2(18 BYTE), 
	"FECHA_ALTA" DATE, 
	"ESTATUS" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"VIGENCIA_DESDE" DATE, 
	"VIGENCIA_HASTA" DATE, 
	"APELLIDOS" VARCHAR2(200 BYTE), 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"ACTIVO" VARCHAR2(20 BYTE), 
	"FOTO" BLOB, 
	"RAZON_RECHAZO" VARCHAR2(255 BYTE), 
	"FECHA_SOLICITUD" DATE, 
	"TELEFONO_CASA" VARCHAR2(20 BYTE), 
	"CORREO" VARCHAR2(255 BYTE), 
	"FECHA_ULT_RECIBO" DATE, 
	"NOMBRE_TUTOR" VARCHAR2(200 BYTE), 
	"APELLIDO_PATERNO" VARCHAR2(100 BYTE), 
	"APELLIDO_MATERNO" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
 LOB ("FOTO") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
ALTER TABLE "ADMIN"."ASOCIADO" ADD PRIMARY KEY ("ID_ASOCIADO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
ALTER TABLE "ADMIN"."ASOCIADO" ADD CONSTRAINT "CHK_ASOCIADO_ESTATUS" CHECK (estatus IN ('pendiente','confirmado','rechazado')) ENABLE;
ALTER TABLE "ADMIN"."ASOCIADO" ADD CONSTRAINT "CHK_ACT_ASC" CHECK (activo in ('Activo', 'Inactivo', 'Anulado', 'Pendiente')) ENABLE;

  CREATE UNIQUE INDEX "ADMIN"."UQ_ASOCIADO_CURP_ACTIVO" ON "ADMIN"."ASOCIADO" (CASE "ACTIVO" WHEN 'Anulado' THEN NULL ELSE "CURP" END ) 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

-- Asociado_direccion

CREATE TABLE "ADMIN"."ASOCIADO_DIRECCION" 
   (	"ID_ASOCIADO" NUMBER NOT NULL ENABLE, 
	"ID_DIRECCION" NUMBER NOT NULL ENABLE, 
	"TIPO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
ALTER TABLE "ADMIN"."ASOCIADO_DIRECCION" ADD CONSTRAINT "PK_ASOCIADO_DIRECCION" PRIMARY KEY ("ID_ASOCIADO", "ID_DIRECCION")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
ALTER TABLE "ADMIN"."ASOCIADO_DIRECCION" ADD CONSTRAINT "CHK_ASODIR_TIPO" CHECK (tipo IN ('principal','emergencia')) ENABLE;
ALTER TABLE "ADMIN"."ASOCIADO_DIRECCION" ADD CONSTRAINT "FK_ASODIR_ASOCIADO" FOREIGN KEY ("ID_ASOCIADO")
	  REFERENCES "ADMIN"."ASOCIADO" ("ID_ASOCIADO") ENABLE;
ALTER TABLE "ADMIN"."ASOCIADO_DIRECCION" ADD CONSTRAINT "FK_ASODIR_DIRECCION" FOREIGN KEY ("ID_DIRECCION")
	  REFERENCES "ADMIN"."DIRECCION" ("ID_DIRECCION") ENABLE;

-- Asociado_padecimiento

CREATE TABLE "ADMIN"."ASOCIADO_PADECIMIENTO" 
   (	"ID_ASOCIADO" NUMBER NOT NULL ENABLE, 
	"ID_PADECIMIENTO" NUMBER NOT NULL ENABLE, 
	"DESCRIPCION_OTRO" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
ALTER TABLE "ADMIN"."ASOCIADO_PADECIMIENTO" ADD CONSTRAINT "PK_ASOCIADO_PADECIMIENTO" PRIMARY KEY ("ID_ASOCIADO", "ID_PADECIMIENTO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
ALTER TABLE "ADMIN"."ASOCIADO_PADECIMIENTO" ADD CONSTRAINT "FK_ASOPAD_ASOCIADO" FOREIGN KEY ("ID_ASOCIADO")
	  REFERENCES "ADMIN"."ASOCIADO" ("ID_ASOCIADO") ENABLE;
ALTER TABLE "ADMIN"."ASOCIADO_PADECIMIENTO" ADD CONSTRAINT "FK_ASOPAD_PADECIMIENTO" FOREIGN KEY ("ID_PADECIMIENTO")
	  REFERENCES "ADMIN"."PADECIMIENTOS" ("ID_PADECIMIENTO") ENABLE;


-- Concepto_recibo

CREATE TABLE "ADMIN"."CONCEPTO_RECIBO" 
   (	"ID_CONCEPTO" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
ALTER TABLE "ADMIN"."CONCEPTO_RECIBO" ADD PRIMARY KEY ("ID_CONCEPTO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
ALTER TABLE "ADMIN"."CONCEPTO_RECIBO" ADD CONSTRAINT "CHK_CONCEPTO_NOMBRE" CHECK (nombre IS NOT NULL) ENABLE;

-- Consulta

CREATE TABLE "ADMIN"."CONSULTA" 
   (	"ID_CONSULTA" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ID_ASOCIADO" NUMBER NOT NULL ENABLE, 
	"ID_MEDICO" NUMBER, 
	"ID_RECIBO" NUMBER, 
	"FECHA" TIMESTAMP (6), 
	"TIPO_CONSULTA" VARCHAR2(20 BYTE), 
	"MOTIVO" CLOB, 
	"DIAGNOSTICO" CLOB, 
	"TRATAMIENTO" CLOB, 
	"APORTACION" NUMBER(10,2), 
	"YA_APORTO" NUMBER(1,0), 
	"ESTATUS" VARCHAR2(50 BYTE), 
	"FECHA_CREACION" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
 LOB ("MOTIVO") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("DIAGNOSTICO") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("TRATAMIENTO") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
ALTER TABLE "ADMIN"."CONSULTA" ADD CHECK (ya_aporto IN (0,1)) ENABLE;
ALTER TABLE "ADMIN"."CONSULTA" ADD PRIMARY KEY ("ID_CONSULTA")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
ALTER TABLE "ADMIN"."CONSULTA" ADD CONSTRAINT "CHK_CONSULTA_TIPO" CHECK (tipo_consulta IN ('primera','seguimiento')) ENABLE;
ALTER TABLE "ADMIN"."CONSULTA" ADD CONSTRAINT "CHK_ESTATUS_CONSULTA" CHECK (estatus in ('Pendiente' , 'En proceso' , 'Completado' , 'Cancelado')) ENABLE;
ALTER TABLE "ADMIN"."CONSULTA" ADD CONSTRAINT "FK_CONSULTA_ASOCIADO" FOREIGN KEY ("ID_ASOCIADO")
	  REFERENCES "ADMIN"."ASOCIADO" ("ID_ASOCIADO") ENABLE;
ALTER TABLE "ADMIN"."CONSULTA" ADD CONSTRAINT "FK_CONSULTA_MEDICO" FOREIGN KEY ("ID_MEDICO")
	  REFERENCES "ADMIN"."MEDICO" ("ID_MEDICO") ENABLE;
ALTER TABLE "ADMIN"."CONSULTA" ADD CONSTRAINT "FK_CONSULTA_RECIBO" FOREIGN KEY ("ID_RECIBO")
	  REFERENCES "ADMIN"."RECIBO" ("ID_RECIBO") ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "ADMIN"."CAMBIOSDEAPORTACIONCONSULTA" 
BEFORE UPDATE OF aportacion
ON consulta
FOR EACH ROW
DECLARE
    diferencia NUMBER;
    total_viejo NUMBER;
    total_pagado_viejo NUMBER;
    v_descuento NUMBER := 0;
BEGIN

    ----------------------------------------------------------------
    -- Skip if no real change
    ----------------------------------------------------------------
    IF NVL(:NEW.aportacion, 0) = NVL(:OLD.aportacion, 0) THEN
        RETURN;
    END IF;

    ----------------------------------------------------------------
    -- No receipt -> nothing to update
    ----------------------------------------------------------------
    IF :OLD.id_recibo IS NULL THEN
        RETURN;
    END IF;

    ----------------------------------------------------------------
    -- Get discount safely
    ----------------------------------------------------------------
    BEGIN
        SELECT NVL(descuento, 0)
        INTO v_descuento
        FROM recibo
        WHERE id_recibo = :OLD.id_recibo;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            v_descuento := 0;
    END;

    ----------------------------------------------------------------
    -- Prevent changes on discounted receipts
    ----------------------------------------------------------------
    IF v_descuento > 0 THEN
        RAISE_APPLICATION_ERROR(
            -20005,
            'No se pueden modificar recibos con descuento'
        );
    END IF;

    ----------------------------------------------------------------
    -- Calculate difference
    ----------------------------------------------------------------
    diferencia := NVL(:NEW.aportacion, 0)
                - NVL(:OLD.aportacion, 0);

    ----------------------------------------------------------------
    -- Validate paid amount
    ----------------------------------------------------------------
    SELECT total, total_pagado
    INTO total_viejo, total_pagado_viejo
    FROM recibo
    WHERE id_recibo = :OLD.id_recibo;

    IF (total_viejo + diferencia) < total_pagado_viejo THEN
        RAISE_APPLICATION_ERROR(
            -20002,
            'No se puede reducir el total debajo del monto pagado'
        );
    END IF;

    ----------------------------------------------------------------
    -- Update receipt
    ----------------------------------------------------------------
    UPDATE recibo
    SET total = total + diferencia
    WHERE id_recibo = :OLD.id_recibo;

END;
/
ALTER TRIGGER "ADMIN"."CAMBIOSDEAPORTACIONCONSULTA" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "ADMIN"."ACTUALIZARPRECIORECIBO" 
before update of id_recibo
on consulta
for each ROW
declare
  total_viejo number;
  total_pagado_viejo number;
  total_movimiento number;
  v_descuento number;
begin

  if (:new.aportacion is not null) then
    total_movimiento :=  :new.aportacion;
  else
    total_movimiento := 0;
  end if;

  if (:new.id_recibo = :old.id_recibo) then
    return;
  end if;

  select descuento into v_descuento from recibo where id_recibo = :new.id_recibo;

  if ((v_descuento is not null) and (v_descuento > 0)) then
    RAISE_APPLICATION_ERROR(-20005,'No se pueden modificar recibos con descuento');
  end if;

  for element in (select * from estudio where id_consulta = :new.id_consulta)
  loop
    if (element.aportacion is not null) THEN
      total_movimiento := total_movimiento + element.aportacion;
    end if;
  end loop;

  if :old.id_recibo is null then
    update recibo set total = total + total_movimiento where id_recibo = :new.id_recibo;
    return;
  end if;
  select total, total_pagado into total_viejo, total_pagado_viejo from recibo where id_recibo = :old.id_recibo;

  if (total_viejo - total_pagado_viejo < total_movimiento) then
    RAISE_APPLICATION_ERROR(-20001, 'No se puede mover un recibo si ya se pagaron las consultas o los recibos siendo relocalizados');
    return;
  end if;

  update recibo set total = total + total_movimiento where id_recibo = :new.id_recibo;
  update recibo set total = total - total_movimiento where id_recibo = :old.id_recibo;

  return;

end;
/
ALTER TRIGGER "ADMIN"."ACTUALIZARPRECIORECIBO" ENABLE;

-- Credencial

CREATE TABLE "ADMIN"."CREDENCIAL" 
   (	"ID_CREDENCIAL" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ID_ASOCIADO" NUMBER NOT NULL ENABLE, 
	"FOLIO" VARCHAR2(50 BYTE), 
	"FECHA_EMISION" DATE, 
	"VIGENCIA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
ALTER TABLE "ADMIN"."CREDENCIAL" ADD PRIMARY KEY ("ID_CREDENCIAL")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
ALTER TABLE "ADMIN"."CREDENCIAL" ADD UNIQUE ("ID_ASOCIADO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
ALTER TABLE "ADMIN"."CREDENCIAL" ADD UNIQUE ("FOLIO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
ALTER TABLE "ADMIN"."CREDENCIAL" ADD CONSTRAINT "FK_CREDENCIAL_ASOCIADO" FOREIGN KEY ("ID_ASOCIADO")
	  REFERENCES "ADMIN"."ASOCIADO" ("ID_ASOCIADO") ENABLE;

-- Detalle_recibo

CREATE TABLE "ADMIN"."DETALLE_RECIBO" 
   (	"ID_DETALLE" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ID_RECIBO" NUMBER NOT NULL ENABLE, 
	"ID_ARTICULO" NUMBER, 
	"ID_CONCEPTO" NUMBER NOT NULL ENABLE, 
	"CANTIDAD" NUMBER NOT NULL ENABLE, 
	"CUOTA_UNITARIA" NUMBER(10,2) NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
ALTER TABLE "ADMIN"."DETALLE_RECIBO" ADD PRIMARY KEY ("ID_DETALLE")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
ALTER TABLE "ADMIN"."DETALLE_RECIBO" ADD CONSTRAINT "FK_DETRECIBO_RECIBO" FOREIGN KEY ("ID_RECIBO")
	  REFERENCES "ADMIN"."RECIBO" ("ID_RECIBO") ENABLE;
ALTER TABLE "ADMIN"."DETALLE_RECIBO" ADD CONSTRAINT "FK_DETRECIBO_ARTICULO" FOREIGN KEY ("ID_ARTICULO")
	  REFERENCES "ADMIN"."ARTICULO" ("ID_ARTICULO") ENABLE;
ALTER TABLE "ADMIN"."DETALLE_RECIBO" ADD CONSTRAINT "FK_DETRECIBO_CONCEPTO" FOREIGN KEY ("ID_CONCEPTO")
	  REFERENCES "ADMIN"."CONCEPTO_RECIBO" ("ID_CONCEPTO") ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "ADMIN"."TRG_TOTAL_RECIBO" 
AFTER INSERT OR UPDATE OR DELETE ON DETALLE_RECIBO
FOR EACH ROW
BEGIN
    UPDATE RECIBO r
    SET total = (
        SELECT NVL(SUM(cantidad * cuota_unitaria),0)
        FROM DETALLE_RECIBO
        WHERE id_recibo = r.id_recibo
    )
    WHERE r.id_recibo = NVL(:NEW.id_recibo, :OLD.id_recibo);
END;

/
ALTER TRIGGER "ADMIN"."TRG_TOTAL_RECIBO" DISABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "ADMIN"."TRG_INVENTARIO_SALIDA" 
AFTER INSERT ON DETALLE_RECIBO
FOR EACH ROW
 WHEN (NEW.id_articulo IS NOT NULL) BEGIN
    -- Descontar inventario
    UPDATE ARTICULO
    SET inventario_actual = inventario_actual - :NEW.cantidad
    WHERE id_articulo = :NEW.id_articulo;

    -- Registrar movimiento
    INSERT INTO MOVIMIENTO_INVENTARIO (
        id_articulo,
        id_recibo,
        fecha,
        tipo,
        cantidad
    ) VALUES (
        :NEW.id_articulo,
        :NEW.id_recibo,
        CURRENT_TIMESTAMP,
        'salida',
        :NEW.cantidad
    );
END;

/
ALTER TRIGGER "ADMIN"."TRG_INVENTARIO_SALIDA" DISABLE;

-- Direccion

CREATE TABLE "ADMIN"."DIRECCION" 
   (	"ID_DIRECCION" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"CALLE" VARCHAR2(200 BYTE), 
	"CIUDAD" VARCHAR2(100 BYTE), 
	"ESTADO" VARCHAR2(100 BYTE), 
	"CP" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
ALTER TABLE "ADMIN"."DIRECCION" ADD PRIMARY KEY ("ID_DIRECCION")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;

-- Estudio

CREATE TABLE "ADMIN"."ESTUDIO" 
   (	"ID_ESTUDIO" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ID_ASOCIADO" NUMBER NOT NULL ENABLE, 
	"ID_MEDICO" NUMBER, 
	"ID_TIPO_ESTUDIO" NUMBER, 
	"LABORATORIO" VARCHAR2(150 BYTE), 
	"FECHA" TIMESTAMP (6), 
	"APORTACION" NUMBER(10,2), 
	"YA_APORTO" NUMBER(1,0), 
	"FECHA_CITA" TIMESTAMP (6), 
	"ESTATUS" VARCHAR2(50 BYTE), 
	"RESULTADOS" CLOB, 
	"ID_CONSULTA" NUMBER, 
	"ID_LABORATORIO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
 LOB ("RESULTADOS") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
ALTER TABLE "ADMIN"."ESTUDIO" ADD CHECK (ya_aporto IN (0,1)) ENABLE;
ALTER TABLE "ADMIN"."ESTUDIO" ADD PRIMARY KEY ("ID_ESTUDIO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
ALTER TABLE "ADMIN"."ESTUDIO" ADD CONSTRAINT "CHK_ESTUDIO_ESTATUS" CHECK (estatus IN ('Pendiente','En proceso','Completado','Cancelado')) ENABLE;
ALTER TABLE "ADMIN"."ESTUDIO" ADD CONSTRAINT "FK_ESTUDIO_ASOCIADO" FOREIGN KEY ("ID_ASOCIADO")
	  REFERENCES "ADMIN"."ASOCIADO" ("ID_ASOCIADO") ENABLE;
ALTER TABLE "ADMIN"."ESTUDIO" ADD CONSTRAINT "FK_ESTUDIO_MEDICO" FOREIGN KEY ("ID_MEDICO")
	  REFERENCES "ADMIN"."MEDICO" ("ID_MEDICO") ENABLE;
ALTER TABLE "ADMIN"."ESTUDIO" ADD CONSTRAINT "FK_ESTUDIO_TIPO_ESTUDIO" FOREIGN KEY ("ID_TIPO_ESTUDIO")
	  REFERENCES "ADMIN"."TIPO_ESTUDIO" ("ID_TIPO_ESTUDIO") ENABLE;
ALTER TABLE "ADMIN"."ESTUDIO" ADD CONSTRAINT "FK_ESTUDIO_CONSULTA" FOREIGN KEY ("ID_CONSULTA")
	  REFERENCES "ADMIN"."CONSULTA" ("ID_CONSULTA") ENABLE;
ALTER TABLE "ADMIN"."ESTUDIO" ADD CONSTRAINT "FK_ESTUDIO_LAB" FOREIGN KEY ("ID_LABORATORIO")
	  REFERENCES "ADMIN"."LABORATORIO" ("ID_LABORATORIO") ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "ADMIN"."ACTUALIZAR_FECHA_ULTIMO_ESTUDIO" 
after insert or update on estudio
for each row
begin
  if :new.id_tipo_estudio = 29 then
    update historial_medico set fecha_ult_gral_orina = :new.fecha_cita where id_asociado = :new.id_asociado;
  elsif :new.id_tipo_estudio = 30 then
    update historial_medico set fecha_ult_eco_renal = :new.fecha_cita where id_asociado = :new.id_asociado;
  elsif :new.id_tipo_estudio = 31 then
    update historial_medico set fecha_ult_est_urodinamico = :new.fecha_cita where id_asociado = :new.id_asociado;
  elsif :new.id_tipo_estudio = 32 then
    update historial_medico set fecha_ult_tac_cerebro= :new.fecha_cita where id_asociado = :new.id_asociado;
  elsif :new.id_tipo_estudio = 33 then
    update historial_medico set fecha_ult_urocultivo = :new.fecha_cita where id_asociado = :new.id_asociado;
  elsif :new.id_tipo_estudio = 34 then
    update historial_medico set fecha_ult_urotac = :new.fecha_cita where id_asociado = :new.id_asociado;
  elsif :new.id_tipo_estudio = 35 then
    update historial_medico set fecha_ult_est_uro = :new.fecha_cita where id_asociado = :new.id_asociado;
  else
    update historial_medico set fecha_ult_otros = :new.fecha_cita where id_asociado = :new.id_asociado;
  end if;
end;
/
ALTER TRIGGER "ADMIN"."ACTUALIZAR_FECHA_ULTIMO_ESTUDIO" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "ADMIN"."CAMBIOSDEAPORTACIONESTUDIO" 
BEFORE UPDATE OF aportacion
ON estudio
FOR EACH ROW
DECLARE
    diferencia NUMBER;
    v_id_recibo NUMBER;
    total_viejo NUMBER;
    total_pagado_viejo NUMBER;
    v_descuento NUMBER := 0;
BEGIN

    ----------------------------------------------------------------
    -- Skip if no real change
    ----------------------------------------------------------------
    IF NVL(:NEW.aportacion, 0) = NVL(:OLD.aportacion, 0) THEN
        RETURN;
    END IF;

    ----------------------------------------------------------------
    -- Find receipt safely
    ----------------------------------------------------------------
    BEGIN
        SELECT id_recibo
        INTO v_id_recibo
        FROM consulta
        WHERE id_consulta = :OLD.id_consulta;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN;
    END;

    ----------------------------------------------------------------
    -- No receipt -> nothing to update
    ----------------------------------------------------------------
    IF v_id_recibo IS NULL THEN
        RETURN;
    END IF;

    ----------------------------------------------------------------
    -- Get discount safely
    ----------------------------------------------------------------
    BEGIN
        SELECT NVL(descuento, 0)
        INTO v_descuento
        FROM recibo
        WHERE id_recibo = v_id_recibo;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            v_descuento := 0;
    END;

    ----------------------------------------------------------------
    -- Prevent changes on discounted receipts
    ----------------------------------------------------------------
    IF v_descuento > 0 THEN
        RAISE_APPLICATION_ERROR(
            -20005,
            'No se pueden modificar recibos con descuento'
        );
    END IF;

    ----------------------------------------------------------------
    -- Calculate difference
    ----------------------------------------------------------------
    diferencia := NVL(:NEW.aportacion, 0)
                - NVL(:OLD.aportacion, 0);

    ----------------------------------------------------------------
    -- Validate paid amount
    ----------------------------------------------------------------
    SELECT total, total_pagado
    INTO total_viejo, total_pagado_viejo
    FROM recibo
    WHERE id_recibo = v_id_recibo;

    IF (total_viejo + diferencia) < total_pagado_viejo THEN
        RAISE_APPLICATION_ERROR(
            -20003,
            'No se puede reducir el total debajo del monto pagado'
        );
    END IF;

    ----------------------------------------------------------------
    -- Update receipt
    ----------------------------------------------------------------
    UPDATE recibo
    SET total = total + diferencia
    WHERE id_recibo = v_id_recibo;

END;
/
ALTER TRIGGER "ADMIN"."CAMBIOSDEAPORTACIONESTUDIO" ENABLE;

-- Historial_embarazo 

CREATE TABLE "ADMIN"."HISTORIAL_EMBARAZO" 
   (	"ID_HISTORIAL_EMB" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ID_PADRE" NUMBER, 
	"CIUDAD_INICIO_EMB" VARCHAR2(150 BYTE), 
	"ACIDO_FOLICO" NUMBER(1,0), 
	"CONTROL_PRENATAL" NUMBER, 
	"EXPOSICION_TOXICOS" NUMBER(1,0), 
	"DESCRIPCION_TOXICO" CLOB, 
	"OTRO_HIJO_DTN" NUMBER(1,0), 
	"FAMILIAR_DTN" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
 LOB ("DESCRIPCION_TOXICO") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
ALTER TABLE "ADMIN"."HISTORIAL_EMBARAZO" ADD CHECK (acido_folico IN (0,1)) ENABLE;
ALTER TABLE "ADMIN"."HISTORIAL_EMBARAZO" ADD CHECK (exposicion_toxicos IN (0,1)) ENABLE;
ALTER TABLE "ADMIN"."HISTORIAL_EMBARAZO" ADD CHECK (otro_hijo_dtn IN (0,1)) ENABLE;
ALTER TABLE "ADMIN"."HISTORIAL_EMBARAZO" ADD CHECK (familiar_dtn IN (0,1)) ENABLE;
ALTER TABLE "ADMIN"."HISTORIAL_EMBARAZO" ADD PRIMARY KEY ("ID_HISTORIAL_EMB")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
ALTER TABLE "ADMIN"."HISTORIAL_EMBARAZO" ADD UNIQUE ("ID_PADRE")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
ALTER TABLE "ADMIN"."HISTORIAL_EMBARAZO" ADD CONSTRAINT "FK_HISTEMB_PADRE" FOREIGN KEY ("ID_PADRE")
	  REFERENCES "ADMIN"."PADRES" ("ID_PADRE") ENABLE;

-- Historial_medico

CREATE TABLE "ADMIN"."HISTORIAL_MEDICO" 
   (	"ID_HISTORIAL" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ID_ASOCIADO" NUMBER NOT NULL ENABLE, 
	"LUGAR_NACIMIENTO" VARCHAR2(150 BYTE), 
	"HOSPITAL" VARCHAR2(150 BYTE), 
	"TIPO_SANGRE" VARCHAR2(5 BYTE), 
	"TIENE_VALVULA" NUMBER(1,0), 
	"NOTAS" CLOB, 
	"ALERGIAS" CLOB, 
	"FECHA_NACIMIENTO" TIMESTAMP (6), 
	"SEXO" VARCHAR2(12 BYTE), 
	"CONTROL_UROLOGICO" NUMBER(1,0) DEFAULT 0, 
	"LUGAR_CONTROL_UROLOGICO" VARCHAR2(150 BYTE), 
	"VIVE" NUMBER(1,0) DEFAULT 1, 
	"FECHA_ULT_GRAL_ORINA" DATE, 
	"FECHA_ULT_ECO_RENAL" DATE, 
	"FECHA_ULT_EST_URODINAMICO" DATE, 
	"FECHA_ULT_TAC_CEREBRO" DATE, 
	"FECHA_ULT_UROCULTIVO" DATE, 
	"FECHA_ULT_UROTAC" DATE, 
	"FECHA_ULT_EST_URO" DATE, 
	"FECHA_ULT_OTROS" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
 LOB ("NOTAS") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("ALERGIAS") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
ALTER TABLE "ADMIN"."HISTORIAL_MEDICO" ADD CHECK (tiene_valvula IN (0,1)) ENABLE;
ALTER TABLE "ADMIN"."HISTORIAL_MEDICO" ADD PRIMARY KEY ("ID_HISTORIAL")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
ALTER TABLE "ADMIN"."HISTORIAL_MEDICO" ADD UNIQUE ("ID_ASOCIADO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
ALTER TABLE "ADMIN"."HISTORIAL_MEDICO" ADD CONSTRAINT "CHK_ASC_SEX" CHECK (sexo in ('Masculino','Femenino')) ENABLE;
ALTER TABLE "ADMIN"."HISTORIAL_MEDICO" ADD CONSTRAINT "FK_HISTMED_ASOCIADO" FOREIGN KEY ("ID_ASOCIADO")
	  REFERENCES "ADMIN"."ASOCIADO" ("ID_ASOCIADO") ENABLE;

-- Laboratorio

CREATE TABLE "ADMIN"."LABORATORIO" 
   (	"ID_LABORATORIO" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(150 BYTE) NOT NULL ENABLE, 
	"DIRECCION" VARCHAR2(300 BYTE), 
	"TELEFONO" VARCHAR2(20 BYTE), 
	"CORREO" VARCHAR2(120 BYTE), 
	"SITIO_WEB" VARCHAR2(200 BYTE), 
	"NOMBRE_CONTACTO" VARCHAR2(120 BYTE), 
	"HORARIO_ATENCION" VARCHAR2(100 BYTE), 
	"ESTATUS" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE, 
	"FECHA_ALTA" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"FECHA_DESACTIVACION" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
ALTER TABLE "ADMIN"."LABORATORIO" ADD PRIMARY KEY ("ID_LABORATORIO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;

-- Log_pagos

CREATE TABLE "ADMIN"."LOG_PAGOS" 
   (	"ID_LOG_PAGO" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ID_RECIBO" NUMBER NOT NULL ENABLE, 
	"CANT_PAGADA" NUMBER NOT NULL ENABLE, 
	"METODO_PAGO" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"FECHA_PAGO" DATE NOT NULL ENABLE, 
	"ID_ASOCIADO" NUMBER NOT NULL ENABLE, 
	"ID_USUARIO" NUMBER NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
ALTER TABLE "ADMIN"."LOG_PAGOS" ADD PRIMARY KEY ("ID_LOG_PAGO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
ALTER TABLE "ADMIN"."LOG_PAGOS" ADD CONSTRAINT "FK_LOG_PAGOS_RECIBO" FOREIGN KEY ("ID_RECIBO")
	  REFERENCES "ADMIN"."RECIBO" ("ID_RECIBO") ON DELETE CASCADE ENABLE;
ALTER TABLE "ADMIN"."LOG_PAGOS" ADD CONSTRAINT "FK_LOG_PAGOS_ASOCIADO" FOREIGN KEY ("ID_ASOCIADO")
	  REFERENCES "ADMIN"."ASOCIADO" ("ID_ASOCIADO") ON DELETE CASCADE ENABLE;
ALTER TABLE "ADMIN"."LOG_PAGOS" ADD CONSTRAINT "FK_LOG_PAGOS_USUARIO" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "ADMIN"."USUARIOS" ("ID_USUARIO") ON DELETE CASCADE ENABLE;

-- Medico

CREATE TABLE "ADMIN"."MEDICO" 
   (	"ID_MEDICO" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(120 BYTE), 
	"ESPECIALIDAD" VARCHAR2(120 BYTE), 
	"TELEFONO" VARCHAR2(20 BYTE), 
	"CORREO" VARCHAR2(120 BYTE), 
	"CEDULA_PROFESIONAL" VARCHAR2(50 BYTE), 
	"APELLIDO" VARCHAR2(120 BYTE), 
	"ESTATUS" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE, 
	"FECHA_ALTA" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"FECHA_DESACTIVACION" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
ALTER TABLE "ADMIN"."MEDICO" ADD PRIMARY KEY ("ID_MEDICO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
ALTER TABLE "ADMIN"."MEDICO" ADD UNIQUE ("CORREO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
ALTER TABLE "ADMIN"."MEDICO" ADD UNIQUE ("CEDULA_PROFESIONAL")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;

-- Metodo_pago

CREATE TABLE "ADMIN"."METODO_PAGO" 
   (	"ID_METODO_PAGO" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(50 BYTE) NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
ALTER TABLE "ADMIN"."METODO_PAGO" ADD PRIMARY KEY ("ID_METODO_PAGO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
ALTER TABLE "ADMIN"."METODO_PAGO" ADD CONSTRAINT "CHK_METODO_PAGO" CHECK (nombre IN ('efectivo','tarjeta','transferencia','deposito')) ENABLE;

-- Movimiento_inventario

CREATE TABLE "ADMIN"."MOVIMIENTO_INVENTARIO" 
   (	"ID_MOVIMIENTO" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ID_ARTICULO" NUMBER NOT NULL ENABLE, 
	"ID_USUARIO" NUMBER, 
	"ID_RECIBO" NUMBER, 
	"FECHA" TIMESTAMP (6), 
	"TIPO" VARCHAR2(10 BYTE), 
	"CANTIDAD" NUMBER, 
	"NOTAS" CLOB, 
	"ES_COMODATO" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"COMODATO_A_QUIEN" VARCHAR2(4000 BYTE), 
	"COMODATO_TIEMPO" VARCHAR2(4000 BYTE), 
	"COMODATO_CONDICIONES" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
 LOB ("NOTAS") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
ALTER TABLE "ADMIN"."MOVIMIENTO_INVENTARIO" ADD PRIMARY KEY ("ID_MOVIMIENTO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
ALTER TABLE "ADMIN"."MOVIMIENTO_INVENTARIO" ADD CONSTRAINT "CHK_MOVINV_TIPO" CHECK (tipo IN ('entrada','salida')) ENABLE;
ALTER TABLE "ADMIN"."MOVIMIENTO_INVENTARIO" ADD CHECK (ES_COMODATO IN (0, 1)) ENABLE;
ALTER TABLE "ADMIN"."MOVIMIENTO_INVENTARIO" ADD CONSTRAINT "FK_MOVINV_ARTICULO" FOREIGN KEY ("ID_ARTICULO")
	  REFERENCES "ADMIN"."ARTICULO" ("ID_ARTICULO") ENABLE;
ALTER TABLE "ADMIN"."MOVIMIENTO_INVENTARIO" ADD CONSTRAINT "FK_MOVINV_USUARIO" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "ADMIN"."USUARIOS" ("ID_USUARIO") ENABLE;
ALTER TABLE "ADMIN"."MOVIMIENTO_INVENTARIO" ADD CONSTRAINT "FK_MOVINV_RECIBO" FOREIGN KEY ("ID_RECIBO")
	  REFERENCES "ADMIN"."RECIBO" ("ID_RECIBO") ENABLE;

  CREATE INDEX "ADMIN"."IX_MOVIMIENTO_RECIBO" ON "ADMIN"."MOVIMIENTO_INVENTARIO" ("ID_RECIBO") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "ADMIN"."TRG_MOVIMIENTO_INVENTARIO_STOCK" 
BEFORE INSERT ON ADMIN.MOVIMIENTO_INVENTARIO
FOR EACH ROW
DECLARE
	v_stock NUMBER;
	v_tipo VARCHAR2(10);
BEGIN
	v_tipo := LOWER(TRIM(:NEW.TIPO));

	IF v_tipo IN ('in', 'entrada') THEN
		v_tipo := 'entrada';
	ELSIF v_tipo IN ('out', 'salida') THEN
		v_tipo := 'salida';
	ELSE
		raise_application_error(-20030, 'TIPO invalid. Use entrada/salida or in/out.');
	END IF;

	IF :NEW.CANTIDAD IS NULL OR :NEW.CANTIDAD <= 0 THEN
		raise_application_error(-20031, 'CANTIDAD must be greater than zero.');
	END IF;

	IF :NEW.FECHA IS NULL THEN
		:NEW.FECHA := SYSTIMESTAMP;
	END IF;

	:NEW.TIPO := v_tipo;

	SELECT NVL(INVENTARIO_ACTUAL, 0)
		INTO v_stock
		FROM ADMIN.ARTICULO
	 WHERE ID_ARTICULO = :NEW.ID_ARTICULO
	 FOR UPDATE;

	IF v_tipo = 'entrada' THEN
		UPDATE ADMIN.ARTICULO
			 SET INVENTARIO_ACTUAL = NVL(INVENTARIO_ACTUAL, 0) + :NEW.CANTIDAD
		 WHERE ID_ARTICULO = :NEW.ID_ARTICULO;
	ELSE
		IF v_stock < :NEW.CANTIDAD THEN
			raise_application_error(-20032, 'Insufficient stock for salida movement.');
		END IF;

		UPDATE ADMIN.ARTICULO
			 SET INVENTARIO_ACTUAL = NVL(INVENTARIO_ACTUAL, 0) - :NEW.CANTIDAD
		 WHERE ID_ARTICULO = :NEW.ID_ARTICULO;
	END IF;
EXCEPTION
	WHEN NO_DATA_FOUND THEN
		raise_application_error(-20033, 'ID_ARTICULO does not exist.');
END;

/
ALTER TRIGGER "ADMIN"."TRG_MOVIMIENTO_INVENTARIO_STOCK" ENABLE;

-- Padecimientos

CREATE TABLE "ADMIN"."PADECIMIENTOS" 
   (	"ID_PADECIMIENTO" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(150 BYTE), 
	"DESCRIPCION" VARCHAR2(300 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
ALTER TABLE "ADMIN"."PADECIMIENTOS" ADD PRIMARY KEY ("ID_PADECIMIENTO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;

-- Padres

CREATE TABLE "ADMIN"."PADRES" 
   (	"ID_PADRE" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ID_ASOCIADO" NUMBER NOT NULL ENABLE, 
	"PARENTESCO" VARCHAR2(10 BYTE), 
	"NOMBRE" VARCHAR2(150 BYTE), 
	"APELLIDO" VARCHAR2(150 BYTE), 
	"LUGAR_NACIMIENTO" VARCHAR2(150 BYTE), 
	"ESCOLARIDAD" VARCHAR2(150 BYTE), 
	"EDAD" NUMBER, 
	"OCUPACION" VARCHAR2(150 BYTE), 
	"SEGURO" VARCHAR2(150 BYTE), 
	"PARENTESCO_ENTRE_PAREJA" NUMBER(1,0), 
	"ADICCIONES" VARCHAR2(300 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
ALTER TABLE "ADMIN"."PADRES" ADD CHECK (parentesco_entre_pareja IN (0,1)) ENABLE;
ALTER TABLE "ADMIN"."PADRES" ADD PRIMARY KEY ("ID_PADRE")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
ALTER TABLE "ADMIN"."PADRES" ADD CONSTRAINT "CHK_PADRES_PARENTESCO" CHECK (parentesco IN ('madre','padre')) ENABLE;
ALTER TABLE "ADMIN"."PADRES" ADD CONSTRAINT "FK_PADRES_ASOCIADO" FOREIGN KEY ("ID_ASOCIADO")
	  REFERENCES "ADMIN"."ASOCIADO" ("ID_ASOCIADO") ENABLE;

-- Pago

CREATE TABLE "ADMIN"."PAGO" 
   (	"ID_PAGO" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ID_RECIBO" NUMBER NOT NULL ENABLE, 
	"ID_METODO_PAGO" NUMBER NOT NULL ENABLE, 
	"MONTO" NUMBER(10,2) NOT NULL ENABLE, 
	"FECHA_PAGO" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
ALTER TABLE "ADMIN"."PAGO" ADD PRIMARY KEY ("ID_PAGO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
ALTER TABLE "ADMIN"."PAGO" ADD CONSTRAINT "FK_PAGO_RECIBO" FOREIGN KEY ("ID_RECIBO")
	  REFERENCES "ADMIN"."RECIBO" ("ID_RECIBO") ENABLE;
ALTER TABLE "ADMIN"."PAGO" ADD CONSTRAINT "FK_PAGO_METODO" FOREIGN KEY ("ID_METODO_PAGO")
	  REFERENCES "ADMIN"."METODO_PAGO" ("ID_METODO_PAGO") ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "ADMIN"."TRG_PAGO_RECIBO" 
AFTER INSERT OR UPDATE OR DELETE ON PAGO
FOR EACH ROW
BEGIN
    UPDATE RECIBO r
    SET total_pagado = (
        SELECT NVL(SUM(monto),0)
        FROM PAGO
        WHERE id_recibo = r.id_recibo
    ),
    saldo_pendiente = NVL(r.total,0) - (
        SELECT NVL(SUM(monto),0)
        FROM PAGO
        WHERE id_recibo = r.id_recibo
    )
    WHERE r.id_recibo = NVL(:NEW.id_recibo, :OLD.id_recibo);
END;

/
ALTER TRIGGER "ADMIN"."TRG_PAGO_RECIBO" DISABLE;

-- Recibo

CREATE TABLE "ADMIN"."RECIBO" 
   (	"ID_RECIBO" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ID_ASOCIADO" NUMBER NOT NULL ENABLE, 
	"ID_USUARIO" NUMBER, 
	"FOLIO" VARCHAR2(50 BYTE), 
	"FECHA" DATE NOT NULL ENABLE, 
	"FECHA_LIMITE" DATE, 
	"TIPO_ZONA" VARCHAR2(10 BYTE), 
	"TIPO_CUOTA" VARCHAR2(10 BYTE), 
	"TOTAL" NUMBER(10,2), 
	"TOTAL_PAGADO" NUMBER(10,2), 
	"SALDO_PENDIENTE" NUMBER(10,2), 
	"ESTATUS" VARCHAR2(20 BYTE), 
	"NOTA" CLOB, 
	"DESCUENTO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
 LOB ("NOTA") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
ALTER TABLE "ADMIN"."RECIBO" ADD PRIMARY KEY ("ID_RECIBO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
ALTER TABLE "ADMIN"."RECIBO" ADD UNIQUE ("FOLIO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
ALTER TABLE "ADMIN"."RECIBO" ADD CONSTRAINT "CHK_RECIBO_ZONA" CHECK (tipo_zona IN ('urbano','rural')) ENABLE;
ALTER TABLE "ADMIN"."RECIBO" ADD CONSTRAINT "CHK_RECIBO_CUOTA" CHECK (tipo_cuota IN ('exento','cuota')) ENABLE;
ALTER TABLE "ADMIN"."RECIBO" ADD CONSTRAINT "CHK_RECIBO_ESTATUS" CHECK (estatus IN ('pagado','parcial','no_pagado')) ENABLE;
ALTER TABLE "ADMIN"."RECIBO" ADD CONSTRAINT "FK_RECIBO_ASOCIADO" FOREIGN KEY ("ID_ASOCIADO")
	  REFERENCES "ADMIN"."ASOCIADO" ("ID_ASOCIADO") ENABLE;
ALTER TABLE "ADMIN"."RECIBO" ADD CONSTRAINT "FK_RECIBO_USUARIO" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "ADMIN"."USUARIOS" ("ID_USUARIO") ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "ADMIN"."ULTIMO_RECIBO_ASOCIADO" 
after insert
on recibo 
for each row
begin

  update asociado set fecha_ult_recibo = :new.fecha where id_asociado = :new.id_asociado;

end;
/
ALTER TRIGGER "ADMIN"."ULTIMO_RECIBO_ASOCIADO" ENABLE;

-- Telefono

CREATE TABLE "ADMIN"."TELEFONO" 
   (	"ID_TELEFONO" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ID_ASOCIADO" NUMBER NOT NULL ENABLE, 
	"TIPO" VARCHAR2(20 BYTE), 
	"NUMERO" VARCHAR2(20 BYTE), 
	"PERSONA_EMERGENCIA" VARCHAR2(100 BYTE), 
	"RELACION_PERSONA_EMERGENCIA" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
ALTER TABLE "ADMIN"."TELEFONO" ADD PRIMARY KEY ("ID_TELEFONO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
ALTER TABLE "ADMIN"."TELEFONO" ADD CONSTRAINT "CHK_TELEFONO_TIPO" CHECK (tipo IN ('casa','cel','trabajo','emergencia')) ENABLE;
ALTER TABLE "ADMIN"."TELEFONO" ADD CONSTRAINT "FK_TELEFONO_ASOCIADO" FOREIGN KEY ("ID_ASOCIADO")
	  REFERENCES "ADMIN"."ASOCIADO" ("ID_ASOCIADO") ENABLE;

-- Tipo_estudio

CREATE TABLE "ADMIN"."TIPO_ESTUDIO" 
   (	"ID_TIPO_ESTUDIO" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(150 BYTE), 
	"DESCRIPCION" VARCHAR2(200 BYTE), 
	"TIEMPO_PREPARACION" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
ALTER TABLE "ADMIN"."TIPO_ESTUDIO" ADD PRIMARY KEY ("ID_TIPO_ESTUDIO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;

-- Usuario

CREATE TABLE "ADMIN"."USUARIOS" 
   (	"ID_USUARIO" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"CORREO" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"PASSWORD_HASH" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"ROL" VARCHAR2(20 BYTE), 
	"FECHA_CREACION" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"ACTIVO" NUMBER(1,0), 
	"PROVIDER" VARCHAR2(20 BYTE), 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"APELLIDOS" VARCHAR2(200 BYTE), 
	"TELEFONO" VARCHAR2(20 BYTE), 
	"FECHA_ACCESO" DATE, 
	"FECHA_DESACTIVADO" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
ALTER TABLE "ADMIN"."USUARIOS" ADD CHECK (activo IN (0,1)) ENABLE;
ALTER TABLE "ADMIN"."USUARIOS" ADD PRIMARY KEY ("ID_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
ALTER TABLE "ADMIN"."USUARIOS" ADD UNIQUE ("CORREO")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
ALTER TABLE "ADMIN"."USUARIOS" ADD CONSTRAINT "CHK_USUARIOS_ROL" CHECK (ROL in ('superadmin', 'admin', 'secretaria', 'CEO')) ENABLE;